name: "TeslaBleHttpProxy"
description: |-
  TeslaBleHttpProxy is a program written in Go that receives HTTP requests and forwards them via Bluetooth to a Tesla vehicle. The program can, for example, be easily used together with evcc.

  The program stores the received requests in a queue and processes them one by one. This ensures that only one Bluetooth connection to the vehicle is established at a time.
version: "0.0.19"
slug: "tesla-ble-http-proxy"
init: false
ingress: true
ingress_port: 8080
ingress_entry: dashboard
stage: experimental
image: wimaha/tesla-ble-http-proxy:2.3.0
url: https://github.com/wimaha/TeslaBleHttpProxy
host_dbus: true
host_network: true
map:
  - type: addon_config
    read_only: false
    path: /key
arch:
  - amd64
  - armv7
  - aarch64
privileged:
  - NET_ADMIN
environment:
  logLevel: debug
